# data_plans.py

DUMMY_PLANS = [
    {
        "id": "HOM_CA_1",
        "insurance_type": "home",
        "company_name": "EverSure Insurance",
        "plan_name": "Essential Home Guard",
        "states": ["CA", "NV", "AZ"],
        "base_annual_premium_usd": 950,
        "monthly_premium_usd": 79.17,
        "coverage_amount_usd": 350_000,
        "deductible_usd": 1000,
        "customer_rating": 4.5,
        "number_of_reviews": 210,
        "features": [
            "Covers fire, theft, and liability",
            "Optional extended replacement cost",
        ],
        "limitations": [
            "No flood coverage",
            "Premium higher in high-risk wildfire zones",
        ],
        "coverage_details": {
            "Dwelling": "$350,000",
            "Personal Property": "$175,000",
            "Liability": "$300,000",
            "Medical Payments": "$5,000",
        },
        "claim_approval_timeline": "7-10 business days",
        "claim_process": "24/7 claims hotline, online filing available",
    },
    {
        "id": "HOM_CA_2",
        "insurance_type": "home",
        "company_name": "Pioneer Mutual",
        "plan_name": "Smart Home Shield",
        "states": ["CA"],
        "base_annual_premium_usd": 780,
        "monthly_premium_usd": 65.00,
        "coverage_amount_usd": 300_000,
        "deductible_usd": 1500,
        "customer_rating": 4.2,
        "number_of_reviews": 95,
        "features": [
            "Bundle discounts with auto",
            "Good claim support reputation",
        ],
        "limitations": [
            "Higher deductible",
            "Limited water backup coverage",
        ],
        "coverage_details": {
            "Dwelling": "$300,000",
            "Personal Property": "$150,000",
            "Liability": "$250,000",
            "Medical Payments": "$3,000",
        },
        "claim_approval_timeline": "5-7 business days",
        "claim_process": "Online portal, phone support, Mobile app for claim filing",
    },
    {
        "id": "FIR_CA_1",
        "insurance_type": "fire",
        "company_name": "SafeFlame Insurance",
        "plan_name": "Fire-Only Essential",
        "states": ["CA", "OR", "WA"],
        "base_annual_premium_usd": 420,
        "monthly_premium_usd": 35.00,
        "coverage_amount_usd": 250_000,
        "deductible_usd": 2000,
        "customer_rating": 4.0,
        "number_of_reviews": 60,
        "features": [
            "Fire and smoke damage only",
            "Designed for high-risk wildfire regions",
        ],
        "limitations": [
            "No theft or liability",
            "Higher deductible for older homes",
        ],
        "coverage_details": {
            "Fire Damage": "$250,000",
            "Smoke Damage": "$100,000",
            "Replacement Cost": "Actual Cash Value",
        },
        "claim_approval_timeline": "10-14 business days",
        "claim_process": "Specialized fire damage assessment, emergency support line",
    },
    {
        "id": "REN_NY_1",
        "insurance_type": "renters",
        "company_name": "CityNest Insurance",
        "plan_name": "Urban Renters Basic",
        "states": ["NY", "NJ", "CT"],
        "base_annual_premium_usd": 210,
        "monthly_premium_usd": 17.50,
        "coverage_amount_usd": 40_000,
        "deductible_usd": 500,
        "customer_rating": 4.6,
        "number_of_reviews": 310,
        "features": [
            "Strong personal property coverage",
            "Good liability protection",
        ],
        "limitations": [
            "Limited coverage for high-value items (jewelry, electronics)",
        ],
        "coverage_details": {
            "Personal Property": "$40,000",
            "Liability": "$300,000",
            "Medical Payments": "$1,000",
            "Loss of Use": "$10,000",
        },
        "claim_approval_timeline": "3-5 business days",
        "claim_process": "Simple online filing, quick approval for standard claims",
    },
    {
        "id": "AUTO_TX_1",
        "insurance_type": "auto",
        "company_name": "RoadGuard Auto",
        "plan_name": "Standard Plus Auto",
        "states": ["TX", "OK", "NM"],
        "base_annual_premium_usd": 680,
        "monthly_premium_usd": 56.67,
        "coverage_amount_usd": 100_000,
        "deductible_usd": 500,
        "customer_rating": 4.3,
        "number_of_reviews": 180,
        "features": [
            "Includes roadside assistance",
            "Accident forgiveness for first claim",
        ],
        "limitations": [
            "Premium can increase after multiple claims",
        ],
        "coverage_details": {
            "Liability": "$100,000/$300,000",
            "Collision": "$100,000 (after deductible)",
            "Comprehensive": "$100,000 (after deductible)",
            "Uninsured/Underinsured": "$100,000",
        },
        "claim_approval_timeline": "4-6 business days",
        "claim_process": "24/7 claims support, Direct repair network, Mobile appraisal",
    },
    {
        "id": "HLT_ALL_1",
        "insurance_type": "health",
        "company_name": "CareFirst Health",
        "plan_name": "Bronze HMO Saver",
        "states": ["ALL"],
        "base_annual_premium_usd": 4200,
        "monthly_premium_usd": 350.00,
        "coverage_amount_usd": 0,
        "deductible_usd": 6000,
        "customer_rating": 3.9,
        "number_of_reviews": 500,
        "features": [
            "Lower monthly premium",
            "Preventive care visits covered",
        ],
        "limitations": [
            "High deductible",
            "Limited network outside metro areas",
        ],
        "coverage_details": {
            "Individual Deductible": "$6,000",
            "Family Deductible": "$12,000",
            "Out-of-Pocket Max": "$8,150 (Individual)",
            "Preventive Care": "100% covered",
        },
        "claim_approval_timeline": "5-10 business days",
        "claim_process": "Online claim submission, insurance portal for tracking",
    },
    {
        "id": "HLT_ALL_2",
        "insurance_type": "health",
        "company_name": "PrimeHealth",
        "plan_name": "Silver PPO Balance",
        "states": ["ALL"],
        "base_annual_premium_usd": 5800,
        "monthly_premium_usd": 483.33,
        "coverage_amount_usd": 0,
        "deductible_usd": 3500,
        "customer_rating": 4.4,
        "number_of_reviews": 260,
        "features": [
            "Better out-of-network coverage",
            "Lower deductible than bronze plans",
        ],
        "limitations": [
            "Higher monthly premium",
        ],
        "coverage_details": {
            "Individual Deductible": "$3,500",
            "Family Deductible": "$7,000",
            "Out-of-Pocket Max": "$6,500 (Individual)",
            "Preventive Care": "100% covered",
        },
        "claim_approval_timeline": "5-10 business days",
        "claim_process": "24/7 customer support, Mobile app, Real-time claim status",
    },
]
